project.name=intyg

artifact.name=webcert
artifact.version=7.5.0.13

sbom.aggregation.module=webcert-web
sbom.aggregation.path=web

git.url=https://github.com/sklintyg/webcert.git
git.branch=main

builder.image=app-builder-image
builder.image.tag=21.0.6

runtime.image=tomcat-base
runtime.image.tag=10.1.52.1

dependencies.common.version=4.3.0.+

dependencies.common.version.resolved=4.3.0.2

build.args=build spotlessCheck testAggregateTestReport camelTest
sonarqube.args=