project.name=intyg
artifact.name=webcert
artifact.version=7.7.0.7
sbom.aggregation.module=webcert-web
sbom.aggregation.path=web
git.url=https://github.com/sklintyg/webcert.git
git.branch=main
builder.image=app-builder-image
builder.image.tag=25.0.3
runtime.image=springboot-base
runtime.image.tag=25.0.1
dependencies.common.version=4.4.0.+
dependencies.common.version.resolved=4.4.0.2
build.args=build spotlessCheck testAggregateTestReport camelTest
sonarqube.args=