package se.inera.webcert.persistence;

public enum Amne {
    KOMPLETTERING_AV_LAKARINTYG,
    MAKULERING_AV_LAKARINTYG,
    AVSTAMNINGSMOTE,
    KONTAKT,
    ARBETSTIDSFORLAGGNING,
    PAMINNELSE,
    OVRIGT
}
