package se.inera.intyg.webcert.persistence.fmb.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import se.inera.intyg.webcert.persistence.fmb.model.Fmb;
import se.inera.intyg.webcert.persistence.fmb.model.FmbCallType;
import se.inera.intyg.webcert.persistence.fmb.model.FmbType;

public interface FmbRepository extends JpaRepository<Fmb, Long> {

    /**
     * Implementation will be generated by Spring Data.
     */
    List<Fmb> findByUrsprung(FmbCallType callType);

    /**
     * Implementation will be generated by Spring Data.
     */
    List<Fmb> findByIcd10AndTyp(String icd10, FmbType type);

}
