package se.inera.webcert 
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._
import scala.concurrent.duration._

class SkrivSigneraSkickaIntyg extends Simulation {

	val testpersonnummer = csv("testpersonnummer_skatteverket.cvs").circular

	val scn = scenario("SkrivSigneraSkicka")
	.exec(Login.loginAs("Åsa-Enhet1"))
	.pause(200 milliseconds)
	.exec(http("Get user details")
				.get("/siths.jsp")
		)
	.pause(50 milliseconds)
	.repeat(10, "i") {
		feed(testpersonnummer)
		.exec(http("Dashboard")
					.get("/views/dashboard/unhandled-qa.html")
					.headers(Headers.default)
		)
		.pause(2 seconds)
		.exec(http("Get statistics")
					.get("/moduleapi/stat/")
					.headers(Headers.json)
		)
		.pause(500 milliseconds)
		.exec(http("Get name from PU-tjanst")
			.get("/api/person/${personNr}")
			.headers(Headers.json)
		)
		.exec(http("Create draft")
			.post("/api/utkast/fk7263")
			.headers(Headers.json)
			.body(StringBody("""{"intygType":"fk7263","patientPersonnummer":"${personNr}","patientFornamn":"test","patientEfternamn":"test"}"""))
			.check(bodyString.saveAs("intyg"))
		)
		.pause(100 milliseconds)
		.exec(http("Get draft certificate")
			.get("/moduleapi/utkast/fk7263/${intyg}")
			.headers(Headers.json)
		)
		.pause(3 seconds)
		.exec(http("Autosave certificate 1")
			.put("/moduleapi/utkast/fk7263/${intyg}?autoSave=true")
			.headers(Headers.json)
			.body(StringBody("""{"id":"${intyg}","grundData":{"skapadAv":{"personId":"IFV1239877878-104B","fullstandigtNamn":"Åsa Andersson","forskrivarKod":"2481632","vardenhet":{"enhetsid":"IFV1239877878-1042","enhetsnamn":"WebCert-Enhet1","postadress":"Storgatan 1","postnummer":"12345","postort":"Småmåla","telefonnummer":"0101234567890","epost":"enhet1@webcert.invalid.se","vardgivare":{"vardgivarid":"IFV1239877878-1041","vardgivarnamn":"WebCert-Vårdgivare1"},"arbetsplatsKod":"0000000"}},"patient":{"personId":"${personNr}","fullstandigtNamn":"test test","fornamn":"test","efternamn":"test","samordningsNummer":false}},"avstangningSmittskydd":false,"rekommendationKontaktArbetsformedlingen":false,"rekommendationKontaktForetagshalsovarden":false,"rekommendationOvrigtCheck":false,"nuvarandeArbete":true,"arbetsloshet":false,"foraldrarledighet":false,"ressattTillArbeteAktuellt":false,"ressattTillArbeteEjAktuellt":true,"kontaktMedFk":false,"forskrivarkodOchArbetsplatskod":"2481632 - 0000000","namnfortydligandeOchAdress":"Åsa Andersson\nWebCert-Enhet1\nStorgatan 1\n12345 Småmåla\n0101234567890","undersokningAvPatienten":"2015-02-20","diagnosKodsystem1":"ICD_10_SE","diagnosKodsystem2":"ICD_10_SE","diagnosKodsystem3":"ICD_10_SE","annanReferensBeskrivning":null,"nuvarandeArbetsuppgifter":null,"rekommendationOvrigt":null,"rehabilitering":"rehabiliteringEjAktuell","nedsattMed25Beskrivning":null,"nedsattMed50Beskrivning":null,"nedsattMed75Beskrivning":null,"nedsattMed100Beskrivning":null,"arbetsformagaPrognosGarInteAttBedomaBeskrivning":null,"prognosBedomning":"arbetsformagaPrognosJa"}"""))
		)
		.pause(2 seconds)
		.exec(http("Lookup code")
			.post("/moduleapi/diagnos/kod/sok")
			.body(StringBody("""{"codeSystem":"ICD_10_SE","codeFragment":"A00","nbrOfResults":10}"""))
			.headers(Headers.json)
		)
		.pause(3 seconds)
		.exec(http("Autosave certificate 2")
			.put("/moduleapi/utkast/fk7263/${intyg}?autoSave=true")
			.headers(Headers.json)
			.body(StringBody("""{"id":"${intyg}","grundData":{"skapadAv":{"personId":"IFV1239877878-104B","fullstandigtNamn":"Åsa Andersson","forskrivarKod":"2481632","vardenhet":{"enhetsid":"IFV1239877878-1042","enhetsnamn":"WebCert-Enhet1","postadress":"Storgatan 1","postnummer":"12345","postort":"Småmåla","telefonnummer":"0101234567890","epost":"enhet1@webcert.invalid.se","vardgivare":{"vardgivarid":"IFV1239877878-1041","vardgivarnamn":"WebCert-Vårdgivare1"},"arbetsplatsKod":"0000000"}},"patient":{"personId":"${personNr}","fullstandigtNamn":"test test","fornamn":"test","efternamn":"test","samordningsNummer":false}},"avstangningSmittskydd":false,"rekommendationKontaktArbetsformedlingen":false,"rekommendationKontaktForetagshalsovarden":false,"rekommendationOvrigtCheck":false,"nuvarandeArbete":true,"arbetsloshet":false,"foraldrarledighet":false,"ressattTillArbeteAktuellt":false,"ressattTillArbeteEjAktuellt":true,"kontaktMedFk":false,"forskrivarkodOchArbetsplatskod":"2481632 - 0000000","namnfortydligandeOchAdress":"Åsa Andersson\nWebCert-Enhet1\nStorgatan 1\n12345 Småmåla\n0101234567890","undersokningAvPatienten":"2015-02-20","diagnosKodsystem1":"ICD_10_SE","diagnosKodsystem2":"ICD_10_SE","diagnosKodsystem3":"ICD_10_SE","annanReferensBeskrivning":null,"nuvarandeArbetsuppgifter":null,"rekommendationOvrigt":null,"rehabilitering":"rehabiliteringEjAktuell","nedsattMed25Beskrivning":null,"nedsattMed50Beskrivning":null,"nedsattMed75Beskrivning":null,"nedsattMed100Beskrivning":null,"arbetsformagaPrognosGarInteAttBedomaBeskrivning":null,"prognosBedomning":"arbetsformagaPrognosJa","diagnosKod":"A00","diagnosBeskrivning1":"Kolera","sjukdomsforlopp":"sjukdom"}"""))
		)
		.pause(5 seconds)
		.exec(http("Autosave certificate 3")
			.put("/moduleapi/utkast/fk7263/${intyg}?autoSave=true")
			.headers(Headers.json)
			.body(StringBody("""{"id":"${intyg}","grundData":{"skapadAv":{"personId":"IFV1239877878-104B","fullstandigtNamn":"Åsa Andersson","forskrivarKod":"2481632","vardenhet":{"enhetsid":"IFV1239877878-1042","enhetsnamn":"WebCert-Enhet1","postadress":"Storgatan 1","postnummer":"12345","postort":"Småmåla","telefonnummer":"0101234567890","epost":"enhet1@webcert.invalid.se","vardgivare":{"vardgivarid":"IFV1239877878-1041","vardgivarnamn":"WebCert-Vårdgivare1"},"arbetsplatsKod":"0000000"}},"patient":{"personId":"${personNr}","fullstandigtNamn":"test test","fornamn":"test","efternamn":"test","samordningsNummer":false}},"avstangningSmittskydd":false,"rekommendationKontaktArbetsformedlingen":false,"rekommendationKontaktForetagshalsovarden":false,"rekommendationOvrigtCheck":false,"nuvarandeArbete":true,"arbetsloshet":false,"foraldrarledighet":false,"ressattTillArbeteAktuellt":false,"ressattTillArbeteEjAktuellt":true,"kontaktMedFk":false,"forskrivarkodOchArbetsplatskod":"2481632 - 0000000","namnfortydligandeOchAdress":"Åsa Andersson\nWebCert-Enhet1\nStorgatan 1\n12345 Småmåla\n0101234567890","undersokningAvPatienten":"2015-02-20","diagnosKodsystem1":"ICD_10_SE","diagnosKodsystem2":"ICD_10_SE","diagnosKodsystem3":"ICD_10_SE","annanReferensBeskrivning":null,"nuvarandeArbetsuppgifter":null,"rekommendationOvrigt":null,"rehabilitering":"rehabiliteringEjAktuell","nedsattMed25Beskrivning":null,"nedsattMed50Beskrivning":null,"nedsattMed75Beskrivning":null,"nedsattMed100Beskrivning":null,"arbetsformagaPrognosGarInteAttBedomaBeskrivning":null,"prognosBedomning":"arbetsformagaPrognosJa","diagnosKod":"A00","diagnosBeskrivning1":"Kolera","sjukdomsforlopp":"sjukdom","funktionsnedsattning":"nedsättning","aktivitetsbegransning":"begränsning"}"""))
		)
		.pause(5 seconds)
		.exec(http("Autosave certificate 4")
			.put("/moduleapi/utkast/fk7263/${intyg}?autoSave=true")
			.headers(Headers.json)
			.body(StringBody("""{"id":"${intyg}","grundData":{"skapadAv":{"personId":"IFV1239877878-104B","fullstandigtNamn":"Åsa Andersson","forskrivarKod":"2481632","vardenhet":{"enhetsid":"IFV1239877878-1042","enhetsnamn":"WebCert-Enhet1","postadress":"Storgatan 1","postnummer":"12345","postort":"Småmåla","telefonnummer":"0101234567890","epost":"enhet1@webcert.invalid.se","vardgivare":{"vardgivarid":"IFV1239877878-1041","vardgivarnamn":"WebCert-Vårdgivare1"},"arbetsplatsKod":"0000000"}},"patient":{"personId":"${personNr}","fullstandigtNamn":"test test","fornamn":"test","efternamn":"test","samordningsNummer":false}},"avstangningSmittskydd":false,"rekommendationKontaktArbetsformedlingen":false,"rekommendationKontaktForetagshalsovarden":false,"rekommendationOvrigtCheck":false,"nuvarandeArbete":true,"arbetsloshet":false,"foraldrarledighet":false,"ressattTillArbeteAktuellt":false,"ressattTillArbeteEjAktuellt":true,"kontaktMedFk":false,"forskrivarkodOchArbetsplatskod":"2481632 - 0000000","namnfortydligandeOchAdress":"Åsa Andersson\nWebCert-Enhet1\nStorgatan 1\n12345 Småmåla\n0101234567890","undersokningAvPatienten":"2015-02-20","diagnosKodsystem1":"ICD_10_SE","diagnosKodsystem2":"ICD_10_SE","diagnosKodsystem3":"ICD_10_SE","annanReferensBeskrivning":null,"nuvarandeArbetsuppgifter":"arbete","rekommendationOvrigt":null,"rehabilitering":"rehabiliteringEjAktuell","nedsattMed25Beskrivning":null,"nedsattMed50Beskrivning":null,"nedsattMed75Beskrivning":null,"nedsattMed100Beskrivning":null,"arbetsformagaPrognosGarInteAttBedomaBeskrivning":null,"prognosBedomning":"arbetsformagaPrognosJa","diagnosKod":"A00","diagnosBeskrivning1":"Kolera","sjukdomsforlopp":"sjukdom","funktionsnedsattning":"nedsättning","aktivitetsbegransning":"begränsning","nedsattMed100":{"from":"2015-02-20","tom":"2015-02-27"}}"""))
		)
		.pause(5 seconds)
		.exec(http("Autosave certificate 5")
			.put("/moduleapi/utkast/fk7263/${intyg}?autoSave=true")
			.headers(Headers.json)
			.body(StringBody("""{"id":"${intyg}","grundData":{"skapadAv":{"personId":"IFV1239877878-104B","fullstandigtNamn":"Åsa Andersson","forskrivarKod":"2481632","vardenhet":{"enhetsid":"IFV1239877878-1042","enhetsnamn":"WebCert-Enhet1","postadress":"Storgatan 1","postnummer":"12345","postort":"Småmåla","telefonnummer":"0101234567890","epost":"enhet1@webcert.invalid.se","vardgivare":{"vardgivarid":"IFV1239877878-1041","vardgivarnamn":"WebCert-Vårdgivare1"},"arbetsplatsKod":"0000000"}},"patient":{"personId":"${personNr}","fullstandigtNamn":"test test","fornamn":"test","efternamn":"test","samordningsNummer":false}},"avstangningSmittskydd":false,"rekommendationKontaktArbetsformedlingen":false,"rekommendationKontaktForetagshalsovarden":false,"rekommendationOvrigtCheck":false,"nuvarandeArbete":true,"arbetsloshet":false,"foraldrarledighet":false,"ressattTillArbeteAktuellt":false,"ressattTillArbeteEjAktuellt":true,"kontaktMedFk":false,"forskrivarkodOchArbetsplatskod":"2481632 - 0000000","namnfortydligandeOchAdress":"Åsa Andersson\nWebCert-Enhet1\nStorgatan 1\n12345 Småmåla\n0101234567890","undersokningAvPatienten":"2015-02-20","diagnosKodsystem1":"ICD_10_SE","diagnosKodsystem2":"ICD_10_SE","diagnosKodsystem3":"ICD_10_SE","annanReferensBeskrivning":null,"nuvarandeArbetsuppgifter":"arbete","rekommendationOvrigt":null,"rehabilitering":"rehabiliteringEjAktuell","nedsattMed25Beskrivning":null,"nedsattMed50Beskrivning":null,"nedsattMed75Beskrivning":null,"arbetsformagaPrognosGarInteAttBedomaBeskrivning":null,"prognosBedomning":"arbetsformagaPrognosJa","diagnosKod":"A00","diagnosBeskrivning1":"Kolera","sjukdomsforlopp":"sjukdom","funktionsnedsattning":"nedsättning","aktivitetsbegransning":"begränsning","nedsattMed100":{"from":"2015-02-20","tom":"2015-02-27"},"kommentar":"Övrigt"}"""))
		)
		.pause(5 seconds)
		.exec(http("Sign certificate")
			.post("/moduleapi/utkast/fk7263/${intyg}/signeraserver")
			.headers(Headers.json)
		)
		.exec(http("Get signature")
			.get("/moduleapi/utkast/fk7263/${intyg}/signeringsstatus")
			.headers(Headers.json)
		)
		.pause(1 seconds)
		.exec(http("Get QAs")
			.get("/moduleapi/fragasvar/fk7263/${intyg}")
			.headers(Headers.json)
		)
	    .exec(http("Get certificate")
			.get("/moduleapi/intyg/fk7263/${intyg}")
			.headers(Headers.json)
		)
		.pause(5 seconds)
		.exec(http("Send certificate")
			.post("/moduleapi/intyg/fk7263/${intyg}/skicka")
			.headers(Headers.json)
			.body(StringBody("""{"recipient":"FK","patientConsent":true}"""))
		)
		.pause(1 seconds)
	    .exec(http("Get signed certificate")
			.get("/moduleapi/intyg/fk7263/${intyg}")
			.headers(Headers.json)
		)
	}
	.exec(http("Logout")
		.get("/logout")
		.headers(Headers.default)
		)
	
	setUp(scn.inject(rampUsers(100) over (120 seconds)).protocols(Conf.httpConf))
}