CREATE TABLE IF NOT EXISTS ID_SEQ_TABLE (
	SEQ_NAME VARCHAR(20) NOT NULL,
	SEQ_VALUE BIGINT NOT NULL,
	PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE IF NOT EXISTS MIGRATED_CERTIFICATE (
	ID BIGINT IDENTITY NOT NULL,  
	CERTIFICATE_ID VARCHAR(255) NOT NULL,
	DOCUMENT BLOB NOT NULL,
	PRIMARY KEY (ID)
);
