DROP TABLE IF EXISTS AUTHORITIES;

DROP TABLE IF EXISTS USERS_CARE_UNIT;

DROP TABLE IF EXISTS CERTIFICATE;

DROP TABLE IF EXISTS COMPLEMENT;

DROP TABLE IF EXISTS QUESTION;

DROP TABLE IF EXISTS CARE_UNIT;

DROP TABLE IF EXISTS CARE_GIVER;

DROP TABLE IF EXISTS DRAFT_ANSWER;

DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS ANSWER;

CREATE TABLE AUTHORITIES (
  ID        VARCHAR(255) NOT NULL,
  AUTHORITY VARCHAR(255) NOT NULL,
  USER_ID   VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE USERS_CARE_UNIT (
  users_ID     VARCHAR(255) NOT NULL,
  careUnits_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (users_ID, careUnits_ID)
);

CREATE TABLE CERTIFICATE (
  ID           VARCHAR(255) NOT NULL,
  CARE_UNIT_ID VARCHAR(255),
  CREATED_AT   DATETIME,
  DOCUMENT     LONGBLOB,
  ORIGIN       VARCHAR(255),
  PATIENT_NAME VARCHAR(255),
  PATIENT_SSN  VARCHAR(255),
  SENT_AT      DATETIME,
  SIGNATURE    LONGBLOB,
  SIGNED_AT    DATETIME,
  STATE        VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE COMPLEMENT (
  ID          BIGINT NOT NULL,
  FALT        VARCHAR(255),
  TEXT        VARCHAR(255),
  QUESTION_ID VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE QUESTION (
  ORIGINATOR               VARCHAR(20)  NOT NULL,
  ID                       VARCHAR(255) NOT NULL,
  CARE_GIVER_ID            VARCHAR(255),
  CARE_GIVER_NAME          VARCHAR(255),
  CARE_PERSON_CODE         VARCHAR(255),
  CARE_PERSON_ID           VARCHAR(255),
  CARE_PERSON_NAME         VARCHAR(255),
  CARE_UNIT_ID             VARCHAR(255),
  CARE_UNIT_NAME           VARCHAR(255),
  CARE_UNIT_WORKPLACE_CODE VARCHAR(255),
  CARE_EMAIL_ADDRESS       VARCHAR(255),
  CARE_PHONE_NUMBER        VARCHAR(255),
  CARE_POSTAL_ADDRESS      VARCHAR(255),
  CARE_POSTAL_CITY         VARCHAR(255),
  CARE_POSTAL_NUMBER       VARCHAR(255),
  FK_CONTACT               VARCHAR(255),
  CAPTION                  VARCHAR(255),
  FK_REFERENCE_ID          VARCHAR(255),
  PATIENT_NAME             VARCHAR(255),
  PATIENT_SSN              VARCHAR(255),
  SENT_AT                  DATETIME,
  STATE                    VARCHAR(255),
  SUBJECT                  VARCHAR(255),
  TEXT                     LONGTEXT,
  TEXT_SIGNED_AT           DATETIME,
  SIGNED_DATA              LONGTEXT,
  LAST_DATE_FOR_ANSWER     DATETIME,
  CERTIFICATE_ID           VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CARE_UNIT (
  ID            VARCHAR(255) NOT NULL,
  EMAIL         VARCHAR(255),
  HSA_ID        VARCHAR(255) NOT NULL,
  NAME          VARCHAR(255) NOT NULL,
  VERSION       INT,
  CARE_GIVER_ID VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE CARE_GIVER (
  ID     VARCHAR(255) NOT NULL,
  EMAIL  VARCHAR(255) NOT NULL,
  HSA_ID VARCHAR(255) NOT NULL,
  NAME   VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DRAFT_ANSWER (
  ID                    BIGINT NOT NULL,
  careGiverId           VARCHAR(255),
  careGiverName         VARCHAR(255),
  carePersonCode        VARCHAR(255),
  carePersonId          VARCHAR(255),
  carePersonName        VARCHAR(255),
  careReferenceId       VARCHAR(255),
  careUnitId            VARCHAR(255),
  careUnitName          VARCHAR(255),
  careUnitWorkplaceCode VARCHAR(255),
  created               DATETIME,
  TEXT                  LONGTEXT,
  PRIMARY KEY (ID)
);

CREATE TABLE USERS (
  ID        VARCHAR(255) NOT NULL,
  ENABLED   BIT          NOT NULL,
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  PASSWORD  VARCHAR(255),
  USERNAME  VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ANSWER (
  ORIGINATOR               VARCHAR(20)  NOT NULL,
  ID                       VARCHAR(255) NOT NULL,
  CARE_GIVER_ID            VARCHAR(255),
  CARE_GIVER_NAME          VARCHAR(255),
  CARE_PERSON_CODE         VARCHAR(255),
  CARE_PERSON_ID           VARCHAR(255),
  CARE_PERSON_NAME         VARCHAR(255),
  CARE_UNIT_ID             VARCHAR(255),
  CARE_UNIT_NAME           VARCHAR(255),
  CARE_UNIT_WORKPLACE_CODE VARCHAR(255),
  CARE_EMAIL_ADDRESS       VARCHAR(255),
  CARE_PHONE_NUMBER        VARCHAR(255),
  CARE_POSTAL_ADDRESS      VARCHAR(255),
  CARE_POSTAL_CITY         VARCHAR(255),
  CARE_POSTAL_NUMBER       VARCHAR(255),
  CREATED                  DATETIME,
  SENT_AT                  DATETIME,
  STATE                    VARCHAR(255),
  TEXT                     LONGTEXT,
  TEXT_SIGNED_AT           DATETIME,
  FK_CONTACT               VARCHAR(255),
  SIGNED_DATA              LONGTEXT,
  QUESTION_ID              VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE INDEX FKE9282BE666581D70 ON QUESTION (CERTIFICATE_ID ASC);

CREATE INDEX FK5956A85B9F7F82DB ON USERS_CARE_UNIT (careUnits_ID ASC);

CREATE UNIQUE INDEX HSA_ID ON CARE_UNIT (HSA_ID ASC);

CREATE INDEX FKFCA492266BD9DED3 ON COMPLEMENT (QUESTION_ID ASC);

CREATE INDEX FKAB62A7014A245F84 ON AUTHORITIES (USER_ID ASC);

CREATE INDEX FK5956A85B43153827 ON USERS_CARE_UNIT (users_ID ASC);

CREATE INDEX FK9AF559F2BD4C9B8D ON CARE_UNIT (CARE_GIVER_ID ASC);

CREATE INDEX FK735D33BEF93FC0A4 ON ANSWER (QUESTION_ID ASC);

CREATE UNIQUE INDEX USERNAME ON USERS (USERNAME ASC);

