#!/bin/bash

format=^[A-Z0-9-]{5,}:.*

# When used as a commit hook, the file name of the commit message is provided as $1
if [[ -n $1 ]]; then
    message=$(cat "$1")
else
    message=$(git show -s --format=%B HEAD)
fi

if [[ ! $message =~ $format ]]; then
    echo "Commit message '$message' does not follow format 'PREFIX:Message' ($format)"
    exit 1
fi

exit 0
