@startuml
title Signering med NetiD-plugin
actor User
participant NetiD
participant Browser

participant BrowserCollectLoop

participant Webcert
participant TicketTracker
participant xmldsig
participant Intygstjänsten

User -> Browser: Påbörja signering
activate Browser
Browser -> Webcert: Signeringshash
activate Webcert
Webcert -> xmldsig: Prepare
activate xmldsig
xmldsig --> Webcert: Partiell signatur
deactivate xmldsig
Webcert -> Webcert: Beräkna hash och skapa SignaturBiljett
Webcert -> TicketTracker: Lagra SignaturBiljett
Webcert --> Browser: SignaturBiljett med id och base64-hash
deactivate Webcert
Browser -/ BrowserCollectLoop: Starta poller

activate BrowserCollectLoop
Browser -/ NetiD: Signera(<SignedInfo/>)
deactivate Browser
activate NetiD
User -/ NetiD: Matar in PIN-kod
NetiD -/ Browser: Signatur och X509
deactivate NetiD

activate Browser
Browser -> Webcert: Signatur och X509
deactivate Browser

activate Webcert
Webcert -> xmldsig: Validera signatur
activate xmldsig
xmldsig --> Webcert: Valideringsresultat
deactivate xmldsig
Webcert -> Webcert: Lagra signatur
Webcert -/ Intygstjänsten: RegisterCertificate
Webcert -> TicketTracker: BiljettStatus SIGNERAD

deactivate Webcert


loop tills signeringsstatus SIGNERAD eller ERROR

BrowserCollectLoop -> Webcert: Hämta status
activate Webcert
Webcert -> TicketTracker: Hämta status
activate TicketTracker
TicketTracker --> Webcert: SignaturBiljett
deactivate TicketTracker
Webcert --> BrowserCollectLoop: SignaturBiljett
deactivate Webcert


alt Om SIGNERAD

BrowserCollectLoop -/ Browser: Ladda signerat intyg
activate Browser
end alt
alt Om ERROR
BrowserCollectLoop -/ Browser: Visa felmeddelande
deactivate BrowserCollectLoop
end alt


end loop

Browser -> User: Visar det signerade intyget
deactivate Browser
@enduml
