@startuml
participant b as "Browser"
participant j as "Journalsystem"

participant s as "Säkerhetstjänsten"

box "Webcert" #F8F8F8
	participant wj as "JwtAuthenticationProvider"
	participant wb as "Webcert backend"
end box

participant HSA

b -> j: Open webcert
activate b
activate j

|||
alt No valid session (Standard SAML authentication)
j -> b: Redirect to IdP with AuthnReq

b -> s: AuthnReq
activate s
s -> s: NetiD / PIN-code stuff..
s -> b: Redirect with SAML assertion
b -> j: SAML assertion

deactivate s

end

|||
alt Has valid SAML assertion
j -> s: Request access token\nwith SAML assertion (RFC7522)\nand client_id/client_secret
activate s
s -> s: Validate assertion\n and client
s -> j: Access Token + Refresh Token
deactivate s
end

j --> b: Redirect to Webcert with token
deactivate j
|||
b -> wj: POST to /oauth/token with auth_token\nand integration parameters as\napplication/x-www-form-urlencoded\nform data.


activate  wj
alt JWKS is not cached
wj -> s: Read JWKS keys
activate s
s --> wj: JWKS keys
deactivate s
end
|||
wj -> wj: Validate token signature\nusing JWKS and extract\nHSA-id
|||
wj -> s: Validate token using introspection
activate s
s --> wj: Validation result
deactivate s

|||
wj -> HSA: Get user authorizations using HSA-id
activate HSA
HSA --> wj: HSA details
deactivate HSA

wj -> wj: Build principal, start session
wj -> b: HTTP 302 redirect\nto /visa/intyg/{guid}/saved\nSet-Cookie: SESSION=<session-id>
deactivate  wj
b -> wb: Request resource /visa/intyg/{guid}/saved
activate wb
|||
wb --> b: Requested resource

deactivate wb

deactivate b

@enduml
