@startuml
autonumber
actor Användare
activate Användare
Användare -> Webbläsare: Vill logga in
activate Webbläsare

Webbläsare -> Webcert: Login request
activate Webcert
Webcert --> Webbläsare: Omdirigering till CGIs IdP
deactivate Webcert
Webbläsare -> "CGI funktionstjänster": SAML authentication request
activate "CGI funktionstjänster"
"CGI funktionstjänster" --> Webbläsare: Frågar efter inloggningsmetod

Användare -> Webbläsare: Väljer inloggningsmetod
Webbläsare -\ "CGI funktionstjänster": Vald inloggningsmetod
deactivate Webbläsare
"CGI funktionstjänster" -> "BankID / NetID": Begär autentisering
deactivate "CGI funktionstjänster"
activate  "BankID / NetID"
Användare -/ "BankID / NetID": Interagerar med NetID/BankID-client

"BankID / NetID" --> "CGI funktionstjänster": Autentisering
deactivate  "BankID / NetID"
activate "CGI funktionstjänster"
Webbläsare <-- "CGI funktionstjänster": SAML identitetsintyg
deactivate "CGI funktionstjänster"
activate Webbläsare

Webbläsare -> Webcert: SAML identitetsintyg
activate Webcert
Webcert -> Webcert: Auktorisering\n(via Privatläkarportalen)
Webcert --> Webbläsare: Begärd sida visas

deactivate Webcert
Användare -> Webbläsare: Börjar arbeta
deactivate Användare
deactivate Webbläsare
@enduml