@startuml
autonumber
actor Actor
activate Actor
Actor -> Webbläsare: Vill logga in

activate Webbläsare
Webbläsare -> Webcert: Login request

Webcert --> Webbläsare: Redirect till Säkerhetstjänsten

Webbläsare -> Säkerhetstjänsten: SAML Authentication Request
activate Säkerhetstjänsten
Säkerhetstjänsten --> Webbläsare: Ber webbläsaren starta NetID plugin
deactivate Säkerhetstjänsten
Webbläsare -\ "NetID plugin": Startar NetID plugin
deactivate Webbläsare

activate "NetID plugin"
Actor -\ "NetID plugin": Sätter in SITHS-kort
"NetID plugin" -> Säkerhetstjänsten: Initierar autentisering

activate Säkerhetstjänsten
Säkerhetstjänsten --> "NetID plugin": Ber om lösenord
deactivate Säkerhetstjänsten

Actor -> "NetID plugin": Anger lösenord


"NetID plugin" --> Säkerhetstjänsten: Autentiserar
deactivate "NetID plugin"
activate Säkerhetstjänsten



Säkerhetstjänsten -> HSA: Hämtar HsaID
activate HSA
HSA --> Säkerhetstjänsten: Användarens HsaID
deactivate HSA

Webbläsare <-- Säkerhetstjänsten: SAML identitetsintyg
deactivate Säkerhetstjänsten
activate Webbläsare

Webbläsare -> Webcert: SAML identitetsintyg
deactivate Webbläsare
activate Webcert
Webcert -> Webcert: Tolka SAML identitetsintyg
Webcert -> HSA: Hämtar medarbetaruppdrag
activate HSA
HSA --> Webcert: Svarar med medarbetaruppdrag
deactivate HSA
alt val av vårdenhet krävs

Webcert -/ Webbläsare: Omdirigerar till sida för val av enhet
activate Webbläsare
Actor -> Webbläsare: Väljer vårdenhet
Webbläsare --/ Webcert: Vald vårdenhet
deactivate Webbläsare
end

Webcert <-> Webcert: Skapar session
Webcert --> Webbläsare: Begärd sida visas
activate Webbläsare
deactivate Webcert
Actor -> Webbläsare: Börjar arbeta
deactivate Webbläsare
deactivate Actor
@enduml




Säkerhetstjänsten -> Webbläsare: Visa HTML för val av medarb. uppdr
Actor -> Webbläsare: Väljer medarbetaruppdrag
Webbläsare -> Säkerhetstjänsten: Medarb. uppdr. valt
deactivate Actor