$("input[id*='date_undersokningAvPatienten_']").click();
$("input[id*='date_kannedomOmPatient_']").click();
$("#underlagFinnsNo").prop("checked", true);
$("#underlagFinnsNo").click();
$("#sjukdomsforlopp").val("Har blivit sjuk, är nu ännu sjukare");
$("#sjukdomsforlopp").change();
$("#diagnoseCode").val("A00").change().blur();
$("#diagnoseDescription").val("Kolera").change().blur();
$("#diagnosgrund").val("I hemmet").change();
$("#nyBedomningDiagnosgrundNo").prop("checked", true);
$("#nyBedomningDiagnosgrundNo").click();
$("#funktionsnedsattningIntellektuell").val("instabil").change();
$("#funktionsnedsattningKommunikation").val("Mycket liten måttligt stor nedsättning").change();
$("#aktivitetsbegransning").val("Kan knappt röra sig").change();
$("#medicinskaForutsattningarForArbete").val("I det närmaste obefintlig").change();
