// Går till kanal "Nordic Medtest - Intygsförvaltningen" -> "Nationell Jenkins"
EPOSTMOTTAGARE = "ec9cf062.inera.se@emea.teams.ms"

notificationSent = false

def sendNotificationOnChange()
{
  if (notificationSent) {
    return
  }
  notificationSent = true

  if (currentBuild.currentResult == 'SUCCESS')
  {
    mail to: EPOSTMOTTAGARE,
      subject: "${currentBuild.projectName} fixat!",
      body: "Jobb '${currentBuild.projectName} [${currentBuild.BUILD_NUMBER}]' går nu BRA igen (status ${currentBuild.currentResult})."
  }
  else
  {
    mail to: EPOSTMOTTAGARE,
      subject: "${currentBuild.projectName} trasigt!",
      body: "Jobb '${currentBuild.projectName} [${currentBuild.BUILD_NUMBER}]' misslyckades med status ${currentBuild.currentResult}."
  }
}

pipeline {

  options {
    timestamps () // Kräver plugin "Timestamper"
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {

    HOME = "${env.WORKSPACE}" // Måste sättas för "npm ci"

    CYPRESS_DIR_REL="test/cypress"
    RESULTAT_DIR_REL="${CYPRESS_DIR_REL}/results"
    RESULTAT_DIR_ABS="${env.WORKSPACE}/${RESULTAT_DIR_REL}"

    RESURSRAPPORTSKRIPTNAMN = "write_resource_stats.sh"
    RESURSSKRIPT_ABS="${env.WORKSPACE}/${CYPRESS_DIR_REL}/${RESURSRAPPORTSKRIPTNAMN}"

    RESURSRAPPORTERINGSFIL_REL="${RESULTAT_DIR_REL}/resursrapporteringsfil.txt"
    RESURSRAPPORTERINGSFIL_ABS="${env.WORKSPACE}/${RESURSRAPPORTERINGSFIL_REL}"
    RESURSINTERVALL=30

    // TODO: cypress-failed-log skriver i dagsläget till <startdir>/cypress/logs oavsett hur
    // man konfigurerar Cypress. Endera låter vi det vara så (katalogen skapas endast när testfall
    // går fel), eller så tas cypress-failed-log-pluginet bort. Det tredje alternativet är att se
    // om en nyare version inför konfiguration av sökväg.
    CYPRESSFAILEDLOGS_REL="${CYPRESS_DIR_REL}/cypress/logs/**/*.json"

    TESTRAPPORTFILPATTERN = "*.xml"

    // Nycklarna till dashboard hanteras här: https://dashboard.cypress.io/#/projects/1diiry/settings
    CYPRESS_RECORD_KEY=credentials('CYPRESS_DASHBOARD_NMT_WEBCERT_KEY_1')

    // Användarnamn och lösenord till mocken som hanterar e.g. PDL-loggar. Tre miljövariabler sätts
    // här, CYPRESS_MOCK_USERNAME_PASSWORD, CYPRESS_MOCK_USERNAME_PASSWORD_USR och
    // CYPRESS_MOCK_USERNAME_PASSWORD_PSW
    CYPRESS_MOCK_USERNAME_PASSWORD=credentials('VALIDATION_MOCK_USERNAME_PASSWORD')

    // Denna variabel måste börja på "CYPRESS" och därefter heta exakt samma som parametern i
    // cypress.json eftersom den då skrivs över
    CYPRESS_intygMockBaseUrl = "https://intyg-validatemock.nordicmedtest.se"
  }

  agent {
    docker {
      // image 'cypress/browsers:chrome69'  // Cypress kan inte spela in videos om man kör Chrome

      // Denna image innehåller allt som krävs för att köra Cypress i Linux med videoinspelning etc.
      image 'cypress/base:10'
      label 'docker-slave'
    }
  }

  stages {

    stage('Verifiera förkrav') {
      steps {
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        dir("${CYPRESS_DIR_REL}") {
          sh 'npm --version'
          sh 'node --version'

          // Slå på Chuck Norris-plugin. Kan tas bort utan negativ påverkan.
          chuckNorris()
        }
      }
    }

    stage('Rensa gamla filer') {
      steps {
        // Testrapporter
        sh "rm -fr '${RESULTAT_DIR_ABS}/${TESTRAPPORTFILPATTERN}'"

        // Loggfiler från tidigare körningar
        sh "rm -fr '${env.WORKSPACE}/.npm/_logs/*.log'"

        // Resursrapporteringfil
        sh "rm -fr '${RESURSRAPPORTERINGSFIL_ABS}'"
      }
    }

    stage('Installera Cypress') {
      steps {
        dir("${CYPRESS_DIR_REL}") {
          sh 'npm ci'
          sh 'npm run cy:verify'

          // Skriv ut en lista med alla installerade Node-moduler
          sh 'npm list'
        }
      }
    }

    stage('Starta resursövervakning') {
      steps {
        // Skapa upp resultatkatalogen ifall den inte redan finns
        sh "mkdir -p ${RESULTAT_DIR_ABS}/"

        // Starta resursskriptet. Jenkins Process Tree Killer kommer att döda
        // processen när jobbet är färdigt.
        sh "${RESURSSKRIPT_ABS} ${RESURSINTERVALL} ${RESURSRAPPORTERINGSFIL_ABS} &"
      }
    }

    stage('Exekvera Cypresstester') {
      steps {
        dir("${CYPRESS_DIR_REL}") {
          sh "npm run test:e2e:electron"
        }
      }
    }

    stage('Success') {
      steps {
        script {
          currentBuild.result = 'SUCCESS'
        }
      }
    }
  }

  post {
    changed {
      // Skicka epost om status för jobbet ändras (ex SUCCESS -> FAILURE)
      sendNotificationOnChange
    }

    always {
      archiveArtifacts artifacts: 'test/cypress/videos/**/*.*', fingerprint: false
      archiveArtifacts artifacts: "${RESURSRAPPORTERINGSFIL_REL}", fingerprint: false
      // TODO: Använd variabler för att hämta JUnit-filer istället för hårdkodade pather
      junit 'test/cypress/results/*.xml'
    }

    failure {
      archiveArtifacts artifacts: 'test/cypress/screenshots/**/*.*', fingerprint: false
      archiveArtifacts artifacts: '.npm/_logs/*.log', fingerprint: false
      archiveArtifacts artifacts: "${CYPRESSFAILEDLOGS_REL}", fingerprint: false
    }
  }
}
