# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# Build is currently not working due to dependencies requiring VPN to download
#on:
#  pull_request:
#    branches: [ release/2021-2 ]

on:
  pull_request:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build camelTest -PcodeQuality -DcommonVersion=3.19.1.+ -DinfraVersion=3.19.1.+
